baseURL = 'https://fromthefuture.nl/matrix-docs'
languageCode = 'en-us'
title = 'Handleiding voor matrix.fromthefuture.nl'
theme = 'relearn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]